
CREATE TABLE `maintenance_schedule` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `scheduleNumber` VARCHAR(50) NOT NULL,
  `vehicleId` INTEGER NOT NULL,
  `assignedDriverId` INTEGER NULL,
  `serviceType` VARCHAR(100) NOT NULL,
  `maintenanceCategory` VARCHAR(100) NOT NULL,
  `dueDate` DATETIME(3) NULL,
  `dueMileage` DOUBLE NULL,
  `scheduledDate` DATETIME(3) NOT NULL,
  `estimatedDurationHours` DOUBLE NULL,
  `priority` VARCHAR(191) NOT NULL DEFAULT 'MEDIUM',
  `reason` VARCHAR(500) NOT NULL,
  `description` VARCHAR(5000) NOT NULL,
  `assignedTechnician` VARCHAR(150) NULL,
  `assignedWorkshop` VARCHAR(150) NULL,
  `serviceLocation` VARCHAR(200) NULL,
  `requiredParts` VARCHAR(5000) NULL,
  `estimatedLabourHours` DOUBLE NULL,
  `estimatedPartsCost` DECIMAL(12,2) NULL,
  `estimatedLabourCost` DECIMAL(12,2) NULL,
  `estimatedTotalCost` DECIMAL(12,2) NULL,
  `status` VARCHAR(191) NOT NULL DEFAULT 'SCHEDULED',
  `approvalStatus` VARCHAR(191) NOT NULL DEFAULT 'PENDING',
  `createdBy` VARCHAR(150) NOT NULL,
  `notes` VARCHAR(5000) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `maintenance_schedule_scheduleNumber_key` (`scheduleNumber`),
  INDEX `maintenance_schedule_vehicleId_idx` (`vehicleId`),
  INDEX `maintenance_schedule_assignedDriverId_idx` (`assignedDriverId`),
  INDEX `maintenance_schedule_scheduledDate_idx` (`scheduledDate`),
  INDEX `maintenance_schedule_status_idx` (`status`),
  CONSTRAINT `maintenance_schedule_vehicleId_fkey` FOREIGN KEY (`vehicleId`) REFERENCES `vehicle` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `maintenance_schedule_assignedDriverId_fkey` FOREIGN KEY (`assignedDriverId`) REFERENCES `driver` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `work_order` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `workOrderNumber` VARCHAR(50) NOT NULL,
  `dateCreated` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `requestedBy` VARCHAR(150) NOT NULL,
  `department` VARCHAR(100) NOT NULL,
  `vehicleId` INTEGER NOT NULL,
  `currentMileage` DOUBLE NULL,
  `maintenanceType` VARCHAR(100) NOT NULL,
  `workDescription` VARCHAR(5000) NOT NULL,
  `faultDescription` VARCHAR(5000) NULL,
  `requestedRepairs` VARCHAR(5000) NULL,
  `priority` VARCHAR(191) NOT NULL DEFAULT 'MEDIUM',
  `estimatedCompletionDate` DATETIME(3) NULL,
  `assignedTechnician` VARCHAR(150) NULL,
  `assignedWorkshop` VARCHAR(150) NULL,
  `supervisor` VARCHAR(150) NULL,
  `requiredSpareParts` VARCHAR(5000) NULL,
  `requiredTools` VARCHAR(5000) NULL,
  `estimatedLabourHours` DOUBLE NULL,
  `estimatedPartsCost` DECIMAL(12,2) NULL,
  `estimatedLabourCost` DECIMAL(12,2) NULL,
  `estimatedTotalCost` DECIMAL(12,2) NULL,
  `status` VARCHAR(191) NOT NULL DEFAULT 'PENDING_APPROVAL',
  `actualCompletionDate` DATETIME(3) NULL,
  `technicianNotes` VARCHAR(5000) NULL,
  `finalCost` DECIMAL(12,2) NULL,
  `managerApproval` BOOLEAN NOT NULL DEFAULT false,
  `managerConfirmation` BOOLEAN NOT NULL DEFAULT false,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `work_order_workOrderNumber_key` (`workOrderNumber`),
  INDEX `work_order_vehicleId_idx` (`vehicleId`),
  INDEX `work_order_status_idx` (`status`),
  INDEX `work_order_dateCreated_idx` (`dateCreated`),
  CONSTRAINT `work_order_vehicleId_fkey` FOREIGN KEY (`vehicleId`) REFERENCES `vehicle` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `repair` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `repairReference` VARCHAR(50) NOT NULL,
  `vehicleId` INTEGER NOT NULL,
  `faultReported` VARCHAR(5000) NOT NULL,
  `dateReported` DATETIME(3) NOT NULL,
  `reportedBy` VARCHAR(150) NOT NULL,
  `faultCategory` VARCHAR(100) NOT NULL,
  `severityLevel` VARCHAR(191) NOT NULL DEFAULT 'MEDIUM',
  `initialDiagnosis` VARCHAR(5000) NULL,
  `repairDate` DATETIME(3) NULL,
  `repairStartTime` DATETIME(3) NULL,
  `repairEndTime` DATETIME(3) NULL,
  `assignedTechnician` VARCHAR(150) NULL,
  `workshop` VARCHAR(150) NULL,
  `repairDescription` VARCHAR(5000) NULL,
  `rootCause` VARCHAR(5000) NULL,
  `correctiveActionTaken` VARCHAR(5000) NULL,
  `partsReplaced` VARCHAR(5000) NULL,
  `partNumbers` VARCHAR(5000) NULL,
  `quantityUsed` INTEGER NULL,
  `supplier` VARCHAR(150) NULL,
  `unitCost` DECIMAL(12,2) NULL,
  `totalPartsCost` DECIMAL(12,2) NULL,
  `labourHours` DOUBLE NULL,
  `hourlyRate` DECIMAL(12,2) NULL,
  `labourCost` DECIMAL(12,2) NULL,
  `additionalCosts` DECIMAL(12,2) NULL,
  `totalRepairCost` DECIMAL(12,2) NULL,
  `vehicleTestConducted` BOOLEAN NOT NULL DEFAULT false,
  `roadworthyStatus` VARCHAR(191) NOT NULL DEFAULT 'PENDING',
  `qualityInspectionResult` VARCHAR(5000) NULL,
  `technicianComments` VARCHAR(5000) NULL,
  `completionDate` DATETIME(3) NULL,
  `repairStatus` VARCHAR(191) NOT NULL DEFAULT 'IN_PROGRESS',
  `supportingDocuments` VARCHAR(5000) NULL,
  `beforePhotoUrl` VARCHAR(1000) NULL,
  `afterPhotoUrl` VARCHAR(1000) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `repair_repairReference_key` (`repairReference`),
  INDEX `repair_vehicleId_idx` (`vehicleId`),
  INDEX `repair_repairStatus_idx` (`repairStatus`),
  INDEX `repair_dateReported_idx` (`dateReported`),
  CONSTRAINT `repair_vehicleId_fkey` FOREIGN KEY (`vehicleId`) REFERENCES `vehicle` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `compliance` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `vehicleId` INTEGER NULL,
  `driverId` INTEGER NULL,
  `itemType` VARCHAR(100) NOT NULL,
  `itemName` VARCHAR(200) NOT NULL,
  `issueDate` DATETIME(3) NULL,
  `expiryDate` DATETIME(3) NULL,
  `status` VARCHAR(191) NOT NULL DEFAULT 'COMPLIANT',
  `referenceNumber` VARCHAR(150) NULL,
  `notes` VARCHAR(5000) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  INDEX `compliance_vehicleId_idx` (`vehicleId`),
  INDEX `compliance_driverId_idx` (`driverId`),
  INDEX `compliance_expiryDate_idx` (`expiryDate`),
  INDEX `compliance_status_idx` (`status`),
  CONSTRAINT `compliance_vehicleId_fkey` FOREIGN KEY (`vehicleId`) REFERENCES `vehicle` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `compliance_driverId_fkey` FOREIGN KEY (`driverId`) REFERENCES `driver` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
