
import { useEffect, useState } from "react";
import { Field, Modal, inputClass } from "./MaintenanceUI";
const blank={vehicleId:"",driverId:"",itemType:"Vehicle",itemName:"",issueDate:"",expiryDate:"",status:"COMPLIANT",referenceNumber:"",notes:""};
const local=v=>v?new Date(v).toISOString().slice(0,16):"";
export default function ComplianceModal({open,item,vehicles,drivers,onClose,onSave}){const[form,setForm]=useState(blank);const eligibleDrivers=form.vehicleId?drivers.filter(d=>new Set((vehicles.find(v=>Number(v.id)===Number(form.vehicleId))?.assignment||[]).filter(a=>a.status==="ACTIVE"&&!a.unassignedAt).map(a=>Number(a.driverId))).has(Number(d.id))):drivers;const[error,setError]=useState("");useEffect(()=>{setForm(item?{...blank,...item,issueDate:local(item.issueDate),expiryDate:local(item.expiryDate)}:{...blank});setError("");},[item,open]);const c=e=>setForm(f=>{const next={...f,[e.target.name]:e.target.value};if(e.target.name==="vehicleId"){const v=vehicles.find(x=>Number(x.id)===Number(e.target.value));const a=(v?.assignment||[]).filter(x=>x.status==="ACTIVE"&&!x.unassignedAt);const currentStillLinked=a.some(x=>Number(x.driverId)===Number(f.driverId));next.driverId=currentStillLinked?String(f.driverId):(a.length?String(a[0].driverId):"");}return next;});const submit=async e=>{e.preventDefault();if(!form.itemName){setError("Compliance item name is required.");return;}if(!form.vehicleId&&!form.driverId){setError("Select a vehicle or driver.");return;}try{await onSave({...form,vehicleId:form.vehicleId?Number(form.vehicleId):null,driverId:form.driverId?Number(form.driverId):null,issueDate:form.issueDate?new Date(form.issueDate).toISOString():null,expiryDate:form.expiryDate?new Date(form.expiryDate).toISOString():null});}catch(e){setError(e?.response?.data?.message||"Unable to save compliance record.");}};return <Modal open={open} onClose={onClose} title={item?"Edit Compliance Item":"Add Compliance Item"} subtitle="Monitor expiry and legal compliance."><form onSubmit={submit} className="grid grid-cols-1 gap-5 md:grid-cols-2">
<Field label="Item Type"><select name="itemType" value={form.itemType} onChange={c} className={inputClass}><option>Vehicle</option><option>Driver</option><option>Maintenance</option><option>Safety</option><option>Documentation</option></select></Field><Field label="Compliance Item"><input name="itemName" value={form.itemName} onChange={c} className={inputClass} placeholder="Insurance, road licence, driver licence..." required/></Field>
<Field label="Vehicle"><select name="vehicleId" value={form.vehicleId} onChange={c} className={inputClass}><option value="">Not vehicle-specific</option>{vehicles.map(v=><option key={v.id} value={v.id}>{v.registration} — {v.make} {v.model}</option>)}</select></Field><Field label="Driver"><select name="driverId" value={form.driverId} onChange={c} className={inputClass}><option value="">Not driver-specific</option>{eligibleDrivers.map(d=><option key={d.id} value={d.id}>{d.firstName} {d.lastName}</option>)}</select></Field>
<Field label="Issue Date"><input type="datetime-local" name="issueDate" value={form.issueDate} onChange={c} className={inputClass}/></Field><Field label="Expiry Date"><input type="datetime-local" name="expiryDate" value={form.expiryDate} onChange={c} className={inputClass}/></Field>
<Field label="Status"><select name="status" value={form.status} onChange={c} className={inputClass}><option>COMPLIANT</option><option>EXPIRING_SOON</option><option>EXPIRED</option><option>MISSING</option></select></Field><Field label="Reference Number"><input name="referenceNumber" value={form.referenceNumber} onChange={c} className={inputClass}/></Field>
<Field label="Notes" className="md:col-span-2"><textarea name="notes" value={form.notes} onChange={c} className={inputClass} rows="4"/></Field>
{error&&<div className="md:col-span-2 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</div>}<div className="md:col-span-2 flex justify-end gap-3"><button type="button" onClick={onClose} className="rounded-lg border px-5 py-2.5">Cancel</button><button className="rounded-lg bg-blue-600 px-5 py-2.5 font-semibold text-white hover:bg-blue-700">{item?"Update":"Save Compliance"}</button></div>
</form></Modal>}
