
import { useEffect, useState } from "react";
import { Field, Modal, inputClass } from "./MaintenanceUI";
import userService from "../../../services/userService";
const blank={workOrderNumber:"",requestedBy:"Fleet Manager",department:"Fleet",vehicleId:"",currentMileage:"",maintenanceType:"Corrective",workDescription:"",faultDescription:"",requestedRepairs:"",priority:"MEDIUM",estimatedCompletionDate:"",assignedTechnician:"",assignedWorkshop:"",supervisor:"",requiredSpareParts:"",requiredTools:"",estimatedLabourHours:"",estimatedPartsCost:"",estimatedLabourCost:"",estimatedTotalCost:"",status:"PENDING_APPROVAL",actualCompletionDate:"",technicianNotes:""};
const local=v=>v?new Date(v).toISOString().slice(0,16):"";
export default function WorkOrderModal({open,item,vehicles,onClose,onSave}){const[form,setForm]=useState(blank);const[error,setError]=useState("");const[mechanics,setMechanics]=useState([]);useEffect(()=>{if(open) userService.list().then(r=>setMechanics((r.data.data||[]).filter(u=>u.role==="TECHNICIAN_MECHANIC"&&u.active))).catch(()=>setMechanics([]));setForm(item?{...blank,...item,estimatedCompletionDate:local(item.estimatedCompletionDate),actualCompletionDate:local(item.actualCompletionDate)}:{...blank});setError("");},[item,open]);const c=e=>{const{name,value,type,checked}=e.target;setForm(f=>({...f,[name]:type==="checkbox"?checked:value}));};const submit=async e=>{e.preventDefault();if(!form.vehicleId||!form.requestedBy||!form.department||!form.maintenanceType||!form.workDescription||!form.assignedTechnician){setError("Vehicle, requester, department, maintenance type, work description and a registered Mechanic are required.");return;}try{await onSave({...form,vehicleId:Number(form.vehicleId),estimatedCompletionDate:form.estimatedCompletionDate?new Date(form.estimatedCompletionDate).toISOString():null,actualCompletionDate:form.actualCompletionDate?new Date(form.actualCompletionDate).toISOString():null});}catch(e){setError(e?.response?.data?.message||"Unable to save work order.");}};return <Modal open={open} onClose={onClose} title={item?"Edit Work Order":"New Work Order"} subtitle="Create and track a maintenance request."><form onSubmit={submit} className="grid grid-cols-1 gap-5 md:grid-cols-2">
<Field label="Work Order Number"><input name="workOrderNumber" value={form.workOrderNumber} onChange={c} className={inputClass} placeholder="WO-2026-0001" required/></Field><Field label="Vehicle"><select name="vehicleId" value={form.vehicleId} onChange={c} className={inputClass} required><option value="">Select vehicle</option>{vehicles.map(v=><option key={v.id} value={v.id}>{v.registration} — {v.make} {v.model}</option>)}</select></Field>
<Field label="Requested By"><input name="requestedBy" value={form.requestedBy} onChange={c} className={inputClass} required/></Field><Field label="Department"><input name="department" value={form.department} onChange={c} className={inputClass} required/></Field>
<Field label="Current Mileage (km)"><input type="number" min="0" name="currentMileage" value={form.currentMileage} onChange={c} className={inputClass}/></Field><Field label="Maintenance Type"><input name="maintenanceType" value={form.maintenanceType} onChange={c} className={inputClass} required/></Field>
<Field label="Priority"><select name="priority" value={form.priority} onChange={c} className={inputClass}><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select></Field><Field label="Status"><select name="status" value={form.status} onChange={c} className={inputClass}>{["PENDING_APPROVAL","APPROVED","ASSIGNED","IN_PROGRESS","AWAITING_PARTS","COMPLETED","CLOSED","CANCELLED"].map(x=><option key={x}>{x}</option>)}</select></Field>
<Field label="Estimated Completion"><input type="datetime-local" name="estimatedCompletionDate" value={form.estimatedCompletionDate} onChange={c} className={inputClass}/></Field><Field label="Mechanic" required><select name="assignedTechnician" value={mechanics.find(m=>m.name===form.assignedTechnician)?.id || ""} onChange={e=>{const mechanic=mechanics.find(u=>String(u.id)===e.target.value);setForm(f=>({...f,assignedTechnician:mechanic?mechanic.name:"",assignedWorkshop:mechanic?.workshop||""}));}} className={inputClass}><option value="">Select registered mechanic</option>{mechanics.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></Field>
<Field label="Workshop"><input name="assignedWorkshop" value={form.assignedWorkshop} onChange={c} className={inputClass}/></Field><Field label="Supervisor"><input name="supervisor" value={form.supervisor} onChange={c} className={inputClass}/></Field>
<Field label="Work Description" className="md:col-span-2"><textarea name="workDescription" value={form.workDescription} onChange={c} className={inputClass} rows="4" required/></Field>
<Field label="Fault Description" className="md:col-span-2"><textarea name="faultDescription" value={form.faultDescription} onChange={c} className={inputClass} rows="3"/></Field>
<Field label="Requested Repairs" className="md:col-span-2"><textarea name="requestedRepairs" value={form.requestedRepairs} onChange={c} className={inputClass} rows="3"/></Field>
<Field label="Required Spare Parts"><textarea name="requiredSpareParts" value={form.requiredSpareParts} onChange={c} className={inputClass} rows="3"/></Field><Field label="Required Tools"><textarea name="requiredTools" value={form.requiredTools} onChange={c} className={inputClass} rows="3"/></Field>
<Field label="Estimated Labour Hours"><input type="number" min="0" step="0.25" name="estimatedLabourHours" value={form.estimatedLabourHours} onChange={c} className={inputClass}/></Field><Field label="Estimated Parts Cost (KSh)"><input type="number" min="0" step="0.01" name="estimatedPartsCost" value={form.estimatedPartsCost} onChange={c} className={inputClass}/></Field>
<Field label="Estimated Labour Cost (KSh)"><input type="number" min="0" step="0.01" name="estimatedLabourCost" value={form.estimatedLabourCost} onChange={c} className={inputClass}/></Field><Field label="Estimated Total Cost (KSh)"><input type="number" min="0" step="0.01" name="estimatedTotalCost" value={form.estimatedTotalCost} onChange={c} className={inputClass}/></Field>
<Field label="Actual Completion"><input type="datetime-local" name="actualCompletionDate" value={form.actualCompletionDate} onChange={c} className={inputClass}/></Field>
<Field label="Mechanic Notes" className="md:col-span-2"><textarea name="technicianNotes" value={form.technicianNotes} onChange={c} className={inputClass} rows="3"/></Field>

{error&&<div className="md:col-span-2 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</div>}<div className="md:col-span-2 flex justify-end gap-3"><button type="button" onClick={onClose} className="rounded-lg border px-5 py-2.5">Cancel</button><button className="rounded-lg bg-blue-600 px-5 py-2.5 font-semibold text-white hover:bg-blue-700">{item?"Update Work Order":"Create Work Order"}</button></div>
</form></Modal>}
