ALTER TABLE `User`
  MODIFY `role` ENUM('ADMIN','DISPATCHER','DRIVER','FLEET_MANAGER','OPERATIONS_MANAGER','MAINTENANCE_COMPLIANCE','TECHNICIAN_MECHANIC') NOT NULL DEFAULT 'FLEET_MANAGER',
  ADD COLUMN `active` BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN `driverId` INTEGER NULL;

CREATE UNIQUE INDEX `User_driverId_key` ON `User`(`driverId`);
CREATE INDEX `User_role_idx` ON `User`(`role`);
CREATE INDEX `User_active_idx` ON `User`(`active`);

ALTER TABLE `User`
  ADD CONSTRAINT `User_driverId_fkey` FOREIGN KEY (`driverId`) REFERENCES `Driver`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
