import {useEffect,useMemo,useState} from "react";
import maintenanceService from "../../services/maintenanceService";

export default function ApprovalReport(){
 const [items,setItems]=useState([]),[type,setType]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{setLoading(true);maintenanceService.getApprovals(type?{entityType:type}:{}).then(setItems).catch(e=>setError(e?.response?.data?.message||"Unable to load approval history.")).finally(()=>setLoading(false))},[type]);
 const summary=useMemo(()=>items.reduce((a,x)=>{a[x.entityType]=(a[x.entityType]||0)+1;return a},{}),[items]);
 return <div className="space-y-6"><div><h1 className="text-3xl font-bold text-slate-900">Approval Summary</h1><p className="mt-1 text-slate-500">Audit trail of maintenance schedule and work order approvals, including who approved each item and when.</p></div><button onClick={()=>window.print()} className="rounded-lg border border-slate-300 bg-white px-4 py-2.5 font-semibold text-slate-700 hover:bg-slate-50">Print / Generate Summary</button><div className="flex flex-wrap gap-3"><select value={type} onChange={e=>setType(e.target.value)} className="rounded-lg border px-4 py-2.5"><option value="">All approval types</option><option value="WORK_ORDER">Work Orders</option><option value="MAINTENANCE_SCHEDULE">Maintenance Schedules</option></select>{Object.entries(summary).map(([k,v])=><span key={k} className="rounded-full bg-blue-50 px-3 py-2 text-sm font-semibold text-blue-700">{k.replaceAll("_"," ")}: {v}</span>)}</div>{error&&<div className="rounded-lg bg-red-50 p-4 text-red-700">{error}</div>}<div className="overflow-x-auto rounded-2xl bg-white shadow-sm ring-1 ring-slate-200"><table className="min-w-full text-sm"><thead className="bg-slate-50"><tr>{["Type","Record","Action","Approved By","Date / Time","Notes"].map(h=><th key={h} className="px-4 py-3 text-left">{h}</th>)}</tr></thead><tbody>{loading?<tr><td colSpan="6" className="p-8 text-center">Loading approval history...</td></tr>:items.map(x=><tr key={x.id} className="border-t"><td className="px-4 py-3">{x.entityType?.replaceAll("_"," ")}</td><td className="px-4 py-3 font-semibold">#{x.entityId}</td><td className="px-4 py-3">{x.action}</td><td className="px-4 py-3">{x.approvedByName||"—"}</td><td className="px-4 py-3">{new Date(x.approvedAt).toLocaleString()}</td><td className="px-4 py-3">{x.notes||"—"}</td></tr>)}{!loading&&!items.length&&<tr><td colSpan="6" className="p-10 text-center text-slate-500">No approvals recorded.</td></tr>}</tbody></table></div></div>
}
