
import { useEffect, useState } from "react";
import { Plus, Search, Pencil, Trash2, Eye } from "lucide-react";
import vehicleService from "../../services/vehicleService"; import driverService from "../../services/driverService"; import assignmentService from "../../services/assignmentService"; import service from "../../services/maintenanceService";
import MaintenanceScheduleModal from "../../features/maintenance/components/MaintenanceScheduleModal";
import ViewMaintenanceModal from "../../features/maintenance/components/ViewMaintenanceModal"; import { formatDate,StatusBadge,Notice } from "../../features/maintenance/components/MaintenanceUI";

export default function MaintenanceSchedule(){const[items,setItems]=useState([]),[vehicles,setVehicles]=useState([]),[drivers,setDrivers]=useState([]),[assignments,setAssignments]=useState([]),[search,setSearch]=useState(""),[editing,setEditing]=useState(null),[viewing,setViewing]=useState(null),[open,setOpen]=useState(false),[error,setError]=useState(""),[loading,setLoading]=useState(true);
const load=async()=>{setLoading(true);try{const[a,b,c,d]=await Promise.all([service.getSchedules(),vehicleService.getAllVehicles(),driverService.getAllDrivers(),assignmentService.getAllAssignments()]);setItems(a);setVehicles(b);setDrivers(c);setAssignments(d);}catch(e){setError(e?.response?.data?.message||"Unable to load schedules.");}finally{setLoading(false)}};useEffect(()=>{load()},[]);
const filtered=items.filter(x=>JSON.stringify(x).toLowerCase().includes(search.toLowerCase()));const save=async d=>{if(editing)await service.updateSchedule(editing.id,d);else await service.createSchedule(d);setOpen(false);setEditing(null);await load()};const view=async id=>{try{setError("");const detail=await service.getSchedule(id);setViewing(detail);}catch(e){setError(e?.response?.data?.message||"Unable to load maintenance schedule details.");}};const del=async id=>{if(confirm("Delete this maintenance schedule?")){await service.deleteSchedule(id);await load()}};
return <div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><h1 className="text-3xl font-bold">Maintenance Schedule</h1><p className="mt-2 text-slate-500">Plan preventive and corrective maintenance.</p></div><button onClick={()=>{setEditing(null);setOpen(true)}} className="flex items-center gap-2 rounded-lg bg-blue-600 px-5 py-3 font-semibold text-white"><Plus size={18}/>New Schedule</button></div>
<div className="flex justify-end"><div className="relative w-full max-w-md"><Search className="absolute left-3 top-3 text-slate-400" size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} className="w-full rounded-lg border px-10 py-2.5" placeholder="Search schedules..."/></div></div>{error&&<Notice>{error}</Notice>}
<div className="overflow-hidden rounded-2xl bg-white shadow-sm ring-1 ring-slate-200"><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50"><tr>{["Schedule","Vehicle","Service","Scheduled","Priority","Status","Actions"].map(h=><th key={h} className="px-4 py-3 text-left font-semibold">{h}</th>)}</tr></thead><tbody>{loading?<tr><td colSpan="7" className="p-8 text-center">Loading...</td></tr>:filtered.length?filtered.map(x=><tr key={x.id} className="border-t hover:bg-slate-50"><td className="px-4 py-3 font-semibold">{x.scheduleNumber}</td><td className="px-4 py-3">{x.vehicle?.registration}</td><td className="px-4 py-3">{x.serviceType}<div className="text-xs text-slate-500">{x.maintenanceCategory}</div></td><td className="px-4 py-3">{formatDate(x.scheduledDate)}</td><td className="px-4 py-3"><StatusBadge value={x.priority}/></td><td className="px-4 py-3"><StatusBadge value={x.status}/></td><td className="px-4 py-3"><div className="flex gap-1"><button title="View" onClick={()=>view(x.id)} className="rounded p-2 text-blue-600 hover:bg-blue-50"><Eye size={17}/></button><button title="Edit" onClick={()=>{setEditing(x);setOpen(true)}} className="rounded p-2 text-amber-600 hover:bg-amber-50"><Pencil size={17}/></button><button title="Delete" onClick={()=>del(x.id)} className="rounded p-2 text-red-600 hover:bg-red-50"><Trash2 size={17}/></button></div></td></tr>):<tr><td colSpan="7" className="p-10 text-center text-slate-500">No schedules found.</td></tr>}</tbody></table></div></div>
<ViewMaintenanceModal open={!!viewing} item={viewing} type="schedule" onClose={()=>setViewing(null)}/>
<MaintenanceScheduleModal open={open} item={editing} vehicles={vehicles} drivers={drivers} assignments={assignments} onClose={()=>{setOpen(false);setEditing(null)}} onSave={save}/></div>}
